// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUfZOZgLDq3rMUD8ieAfNoct3M2IyjqRo',
    appId: '1:162111442440:web:fbb660ae90d9263afacbbd',
    messagingSenderId: '162111442440',
    projectId: 'gaingerms-a9626',
    authDomain: 'gaingerms-a9626.firebaseapp.com',
    storageBucket: 'gaingerms-a9626.appspot.com',
    measurementId: 'G-3XF1TQWHR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbzVMcKCsFWCij7CX3kBgky5-qa3qd-lY',
    appId: '1:162111442440:android:029b19c94a5c4a86facbbd',
    messagingSenderId: '162111442440',
    projectId: 'gaingerms-a9626',
    storageBucket: 'gaingerms-a9626.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3Nnj_mXax7_K44AkiTm1mv2BJkuzivqw',
    appId: '1:162111442440:ios:586996219baf8237facbbd',
    messagingSenderId: '162111442440',
    projectId: 'gaingerms-a9626',
    storageBucket: 'gaingerms-a9626.appspot.com',
    iosClientId: '162111442440-6if9ppoj4ja9q040d5gvpb4ihca092gm.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3Nnj_mXax7_K44AkiTm1mv2BJkuzivqw',
    appId: '1:162111442440:ios:586996219baf8237facbbd',
    messagingSenderId: '162111442440',
    projectId: 'gaingerms-a9626',
    storageBucket: 'gaingerms-a9626.appspot.com',
    iosClientId: '162111442440-6if9ppoj4ja9q040d5gvpb4ihca092gm.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );
}
